In [1]:
import numpy as np
from PIL import Image
import pip as plt
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Dropout,Flatten,Dense

# Process Images

In [2]:
categories =['apple','banana','mixed','orange']

def process_img(file,numlist,features,label):
    for category in categories:
        
        for i in numlist:
            try:
                img= Image.open('%s/%s_%d.jpg' % (file,category,i)).convert('RGB')
                img=img.resize((300,300))
                img_array=np.array(img)
                x=features.append(img_array)
                y=label.append(category)
                       
            except Exception as e:
                pass
        
        continue        

In [3]:
#set up train & test data
x_train=[]
y_train=[]
x_test=[]
y_test=[]

process_img('train',range(1,77),x_train,y_train)
process_img('test',range(21,96),x_test,y_test)  


C:\Users\Evans\anaconda3\envs\tf\lib\site-packages\PIL\Image.py:962: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


In [4]:
#convert to numpy array
x_train=np.array(x_train)
y_train=np.array(y_train)
x_test=np.array(x_test)
y_test=np.array(y_test)

In [5]:
print(x_test)
print(y_test)

[[[[204 230 229]
   [206 232 231]
   [213 239 240]
   ...
   [194 204 132]
   [231 238 161]
   [211 214 135]]

  [[200 225 226]
   [201 226 227]
   [211 235 237]
   ...
   [172 183 115]
   [217 226 151]
   [206 211 131]]

  [[193 217 220]
   [194 218 221]
   [208 232 235]
   ...
   [142 155  92]
   [200 211 139]
   [203 211 132]]

  ...

  [[ 75  88  53]
   [116 128  80]
   [140 148  89]
   ...
   [ 14  41   2]
   [ 51  78  29]
   [ 92 118  62]]

  [[ 80  94  59]
   [105 117  72]
   [120 131  76]
   ...
   [ 15  51  15]
   [ 57  93  47]
   [ 97 130  77]]

  [[ 81  95  60]
   [ 97 110  67]
   [106 119  66]
   ...
   [ 18  59  24]
   [ 62 102  57]
   [ 94 131  79]]]


 [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255

In [6]:
print(x_train)
print(y_train)

[[[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  ...

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]]


 [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255

In [7]:
x_train=np.reshape(x_train,(x_train.shape[0],300,300,3))
x_test=np.reshape(x_test,(x_test.shape[0],300,300,3))

x_train = x_train/255
x_test=x_test/255

In [8]:
#one_hot encoding
encoder=LabelEncoder()
train=encoder.fit_transform(y_train)
test=encoder.fit_transform(y_test)

y_train=tf.keras.utils.to_categorical(train,4)
y_test=tf.keras.utils.to_categorical(test,4)

In [9]:
print (y_test)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


# Run CNN Model

In [10]:
model=Sequential()
model.add(Conv2D(64,(3,3),activation='relu',input_shape=(300,300,3)))
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(4,activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 298, 298, 64)      1792      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 296, 296, 32)      18464     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 148, 148, 32)      0         
_________________________________________________________________
flatten (Flatten)            (None, 700928)            0         
_________________________________________________________________
dense (Dense)                (None, 128)               89718912  
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 5

In [11]:
model.fit(x_train,y_train,epochs=20,validation_split=0.1)


Epoch 1/20
7/7 [==============================] - 91s 13s/step - loss: 24.0838 - accuracy: 0.3704 - val_loss: 1.3916 - val_accuracy: 0.3750
Epoch 2/20
7/7 [==============================] - 88s 13s/step - loss: 1.1183 - accuracy: 0.6620 - val_loss: 0.8379 - val_accuracy: 0.7500
Epoch 3/20
7/7 [==============================] - 60s 9s/step - loss: 1.0640 - accuracy: 0.5324 - val_loss: 0.9507 - val_accuracy: 0.6250
Epoch 4/20
7/7 [==============================] - 62s 9s/step - loss: 1.1225 - accuracy: 0.6620 - val_loss: 1.3774 - val_accuracy: 0.2917
Epoch 5/20
7/7 [==============================] - 66s 9s/step - loss: 0.6696 - accuracy: 0.8519 - val_loss: 0.9870 - val_accuracy: 0.5417
Epoch 6/20
7/7 [==============================] - 75s 11s/step - loss: 0.6424 - accuracy: 0.8472 - val_loss: 0.9316 - val_accuracy: 0.5417
Epoch 7/20
7/7 [==============================] - 101s 14s/step - loss: 0.5319 - accuracy: 0.8796 - val_loss: 1.1577 - val_accuracy: 0.5417
Epoch 8/20
7/7 [============

# Evaluate Accuracy

In [12]:
score=model.evaluate(x_test,y_test)
print('score=',score)

2/2 [==============================] - 1s 736ms/step - loss: 1.4088 - accuracy: 0.6500
score= [1.4087696075439453, 0.6499999761581421]
